package openapi

import (
	"fmt"
	"net/http"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/starwalkn/aastro"
)

// Options controls document generation.
type Options struct {
	// OASVersion is "3.1" (default) or "3.0".
	OASVersion string
	// Title overrides info.title; defaults to the gateway service name.
	Title string
	// APIVersion sets info.version; defaults to "0.0.0".
	APIVersion string
	// Servers become the servers[] section, in the given order.
	Servers []string
	// Extensions enables x-aastro round-trip snapshots on every operation.
	Extensions bool
	// GeneratorVersion is stamped into x-aastro.generator (e.g. aastroctl version).
	GeneratorVersion string
}

type Warning struct {
	Flow    string
	Message string
}

func (w Warning) String() string {
	return fmt.Sprintf("%s: %s", w.Flow, w.Message)
}

const (
	oasVersion31 = "3.1.0"
	oasVersion30 = "3.0.3"

	methodQuery = "QUERY"

	maxBodySizeNote = "Request bodies larger than 5 MiB are rejected with 413."

	schemaProblemDetails = "#/components/schemas/ProblemDetails"

	securitySchemeBearer = "bearerAuth"

	authMiddlewareName = "auth"
)

var defaultUpstream = aastro.DefaultUpstreamConfig()
var pathParamPattern = regexp.MustCompile(`\{([^}]+)\}`)

// FromConfig builds an OpenAPI document from a fully loaded gateway config.
func FromConfig(cfg aastro.Config, opts Options) (*Document, []Warning, error) {
	version, err := resolveOASVersion(opts.OASVersion)
	if err != nil {
		return nil, nil, err
	}

	doc := &Document{
		OpenAPI: version,
		Info: Info{
			Title:       coalesce(opts.Title, cfg.Gateway.Service.Name, "aastro gateway"),
			Description: "Generated by aastroctl from the aastro gateway configuration.",
			Version:     coalesce(opts.APIVersion, "0.0.0"),
		},
		Paths: make(map[string]*PathItem, len(cfg.Gateway.Routing.Flows)),
		XAastro: &RootExtension{
			Schema:    cfg.Schema,
			Generator: "aastroctl/" + coalesce(opts.GeneratorVersion, "dev"),
		},
	}

	for _, s := range opts.Servers {
		doc.Servers = append(doc.Servers, Server{URL: s})
	}

	var warnings []Warning

	rateLimited := cfg.Gateway.Routing.RateLimiter.Enabled
	tags := make(map[string]struct{})

	needProblemSchemas := len(cfg.Gateway.Routing.Flows) > 0

	var needAuthScheme bool

	for _, f := range cfg.Gateway.Routing.Flows {
		auth := findAuthMiddleware(f)
		if auth != nil {
			needAuthScheme = true
		}

		op := buildOperation(f, auth, rateLimited, opts.Extensions)

		if tag := firstPathSegment(f.Path); tag != "" {
			op.Tags = []string{tag}
			tags[tag] = struct{}{}
		}

		item := doc.Paths[f.Path]
		if item == nil {
			item = &PathItem{}
			doc.Paths[f.Path] = item
		}

		ws := attachOperation(item, f, op)
		warnings = append(warnings, ws...)
	}

	for t := range tags {
		doc.Tags = append(doc.Tags, Tag{Name: t})
	}
	sort.Slice(doc.Tags, func(i, j int) bool { return doc.Tags[i].Name < doc.Tags[j].Name })

	if needProblemSchemas || needAuthScheme {
		doc.Components = &Components{}

		if needProblemSchemas {
			doc.Components.Schemas = problemSchemas()
		}

		if needAuthScheme {
			doc.Components.SecuritySchemes = map[string]*SecurityScheme{
				securitySchemeBearer: {
					Type:         "http",
					Scheme:       "bearer",
					BearerFormat: "JWT",
					Description:  "JWT bearer token validated by the gateway auth middleware.",
				},
			}
		}
	}

	return doc, warnings, nil
}

func resolveOASVersion(v string) (string, error) {
	switch v {
	case "", "3.1":
		return oasVersion31, nil
	case "3.0":
		return oasVersion30, nil
	default:
		return "", fmt.Errorf("unsupported OpenAPI version %q (want 3.0 or 3.1)", v)
	}
}

func attachOperation(item *PathItem, f aastro.FlowConfig, op *Operation) []Warning {
	flowID := f.Method + " " + f.Path

	slot := map[string]**Operation{
		"GET":     &item.Get,
		"PUT":     &item.Put,
		"POST":    &item.Post,
		"DELETE":  &item.Delete,
		"OPTIONS": &item.Options,
		"HEAD":    &item.Head,
		"PATCH":   &item.Patch,
	}[f.Method]

	if f.Method == methodQuery {
		slot = &item.XAastroQuery

		if *slot == nil {
			*slot = op
			return []Warning{{
				Flow:    flowID,
				Message: "QUERY is not an OpenAPI 3.x method; emitted as x-aastro-query extension",
			}}
		}

		return []Warning{{Flow: flowID, Message: "duplicate method+path, operation skipped"}}
	}

	if slot == nil {
		return []Warning{{Flow: flowID, Message: fmt.Sprintf("unsupported method %q, flow skipped", f.Method)}}
	}

	if *slot != nil {
		return []Warning{{Flow: flowID, Message: "duplicate method+path, operation skipped"}}
	}

	*slot = op

	return nil
}

func buildOperation(f aastro.FlowConfig, auth *aastro.MiddlewareConfig, rateLimited, extensions bool) *Operation {
	op := &Operation{
		Summary:     summarize(f),
		OperationID: operationID(f.Method, f.Path),
		Parameters:  buildParameters(f),
	}

	notes := descriptionNotes(f)

	if auth != nil {
		op.Security = []map[string][]string{{securitySchemeBearer: {}}}

		if n := authNote(auth); n != "" {
			notes = append(notes, n)
		}
	}

	if hasRequestBody(f.Method) {
		op.RequestBody = &RequestBody{
			Description: maxBodySizeNote,
			Content: map[string]MediaType{
				"application/json": {Schema: &Schema{Type: "object"}},
			},
		}
	}

	switch {
	case f.Streaming:
		op.Responses = streamingResponses(rateLimited)
		notes = append(notes,
			"Streaming flow: the upstream response is streamed to the client unbuffered (SSE-capable); status and body are proxied as-is.")
	case len(f.Upstreams) == 1:
		op.Responses = proxyResponses(rateLimited)
		notes = append(notes,
			"Proxy flow: the upstream's response (status, headers, body) is forwarded to the client as-is. "+
				"Only a gateway-side failure - the upstream is unavailable, returns a server error, or fails "+
				"gateway policy - is reported through the JSON error envelope instead.")
	default:
		op.Responses = aggregateResponses(f, rateLimited)
	}

	if auth != nil {
		op.Responses["401"] = unauthorizedResponse()
	}

	if len(notes) > 0 {
		op.Description = strings.Join(notes, "\n\n")
	}

	if extensions {
		op.XAastro = flowExtension(f)
	}

	return op
}

func summarize(f aastro.FlowConfig) string {
	if f.Streaming {
		return fmt.Sprintf("Proxy to %s (streaming)", upstreamNames(f.Upstreams))
	}

	if len(f.Upstreams) == 1 {
		return fmt.Sprintf("Proxy to %s", upstreamNames(f.Upstreams))
	}

	strategy := ""
	if f.Aggregation != nil {
		strategy = f.Aggregation.Strategy
	}

	return fmt.Sprintf("Aggregate %s (%s)", upstreamNames(f.Upstreams), strategy)
}

func upstreamNames(ups []aastro.UpstreamConfig) string {
	names := make([]string, 0, len(ups))
	for _, u := range ups {
		names = append(names, u.Name)
	}

	return strings.Join(names, ", ")
}

func buildParameters(f aastro.FlowConfig) []Parameter {
	var params []Parameter

	seen := make(map[string]struct{})

	for _, m := range pathParamPattern.FindAllStringSubmatch(f.Path, -1) {
		name := m[1]
		if _, ok := seen[name]; ok {
			continue
		}

		seen[name] = struct{}{}

		params = append(params, Parameter{
			Name:     name,
			In:       "path",
			Required: true,
			Schema:   &Schema{Type: "string"},
		})
	}

	for _, q := range collectForwarded(f.Upstreams, func(u aastro.UpstreamConfig) []string { return u.ForwardQueries }) {
		params = append(params, Parameter{
			Name:   q,
			In:     "query",
			Schema: &Schema{Type: "string"},
		})
	}

	for _, h := range collectForwarded(f.Upstreams, func(u aastro.UpstreamConfig) []string { return u.ForwardHeaders }) {
		switch http.CanonicalHeaderKey(h) {
		case "Accept", "Content-Type", "Authorization":
			continue
		}

		params = append(params, Parameter{
			Name:   h,
			In:     "header",
			Schema: &Schema{Type: "string"},
		})
	}

	return params
}

func collectForwarded(ups []aastro.UpstreamConfig, get func(aastro.UpstreamConfig) []string) []string {
	set := make(map[string]struct{})

	for _, u := range ups {
		for _, name := range get(u) {
			if name == "*" || strings.HasSuffix(name, "*") {
				continue
			}

			set[name] = struct{}{}
		}
	}

	out := make([]string, 0, len(set))
	for name := range set {
		out = append(out, name)
	}

	sort.Strings(out)

	return out
}

func descriptionNotes(f aastro.FlowConfig) []string {
	var notes []string

	var wildcardQueries, wildcardHeaders bool

	var headerPrefixes []string

	for _, u := range f.Upstreams {
		for _, q := range u.ForwardQueries {
			if q == "*" {
				wildcardQueries = true
			}
		}

		for _, h := range u.ForwardHeaders {
			switch {
			case h == "*":
				wildcardHeaders = true
			case strings.HasSuffix(h, "*"):
				headerPrefixes = append(headerPrefixes, h)
			}
		}
	}

	if wildcardQueries {
		notes = append(notes, "All query parameters are forwarded to at least one upstream (`forward_queries: \"*\"`).")
	}

	if wildcardHeaders {
		notes = append(notes, "All request headers are forwarded to at least one upstream (`forward_headers: \"*\"`).")
	}

	if len(headerPrefixes) > 0 {
		sort.Strings(headerPrefixes)
		notes = append(notes, fmt.Sprintf("Headers matching prefix pattern(s) %s are forwarded.", strings.Join(headerPrefixes, ", ")))
	}

	return notes
}

func hasRequestBody(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH", methodQuery:
		return true
	default:
		return false
	}
}

// aggregateResponses is used for a flow with more than one upstream. Success
// and partial success (206, bestEffort) return the aggregated data itself -
// its shape depends on the flow's upstreams and aggregation strategy, so,
// like proxyResponses's 200, it is undocumented content rather than a
// schema ref. Only a response with no data at all (every upstream failed)
// uses the Problem Details schema.
func aggregateResponses(f aastro.FlowConfig, rateLimited bool) map[string]*Response {
	rs := map[string]*Response{
		"200": {
			Description: "Aggregated upstream data (`merge`/`array`/`namespace`), with no gateway wrapper.",
			Headers:     stdHeaders(),
			Content:     map[string]MediaType{"application/json": {}},
		},
		"413": problemResponse("Request body exceeds the gateway limit."),
		"502": problemResponse("Every upstream failed, was unavailable, or returned a malformed response."),
		"500": problemResponse("Internal gateway error."),
	}

	if f.Aggregation != nil {
		if f.Aggregation.BestEffort && len(f.Upstreams) > 1 {
			rs["206"] = &Response{
				Description: "Partial success: some upstreams failed (best-effort aggregation). The body is the data from the " +
					"upstreams that succeeded, in the same shape as 200; `X-Partial-Errors` carries one value per failure.",
				Headers: partialHeaders(),
				Content: map[string]MediaType{"application/json": {}},
			}
		}

		if f.Aggregation.Strategy == "merge" &&
			f.Aggregation.OnConflict != nil &&
			f.Aggregation.OnConflict.Policy == "error" {
			rs["409"] = problemResponse("Merge conflict: upstreams returned different values for the same field (`on_conflict: error`).")
		}
	}

	if rateLimited {
		rs["429"] = problemResponse("Rate limit exceeded.")
	}

	rs["default"] = &Response{
		Description: propagationNote(),
		Headers:     stdHeaders(),
		Content: map[string]MediaType{
			"application/problem+json": {Schema: &Schema{Ref: schemaProblemDetails}},
		},
	}

	return rs
}

// proxyResponses is used for a flow with exactly one upstream: it is not
// aggregated (see Router.dispatch), so its answer is forwarded to the client
// as-is rather than wrapped in a gateway shape. The 200 entry is necessarily
// opaque - the gateway has no static knowledge of the upstream's schema,
// only that *something* comes back unmodified.
func proxyResponses(rateLimited bool) map[string]*Response {
	rs := map[string]*Response{
		"200": {
			Description: "Upstream response forwarded as-is: status, headers, and body are exactly what the upstream returned. " +
				"This also covers 3xx/4xx answers from the upstream - those are proxied verbatim too, not translated into gateway errors.",
			Headers: stdHeaders(),
			Content: map[string]MediaType{"*/*": {}},
		},
		"413": problemResponse("Request body exceeds the gateway limit."),
		"502": problemResponse("Upstream unavailable, returned a server error, or failed gateway policy validation."),
		"500": problemResponse("Internal gateway error."),
	}

	if rateLimited {
		rs["429"] = problemResponse("Rate limit exceeded.")
	}

	return rs
}

func streamingResponses(rateLimited bool) map[string]*Response {
	rs := map[string]*Response{
		"200": {
			Description: "Upstream response streamed as-is. The actual status code, headers, and body are those returned by the upstream.",
			Headers:     stdHeaders(),
			Content:     map[string]MediaType{"*/*": {}},
		},
		"502": problemResponse("Upstream unavailable before the response started streaming."),
		"500": problemResponse("Internal gateway error."),
	}

	if rateLimited {
		rs["429"] = problemResponse("Rate limit exceeded.")
	}

	return rs
}

// problemResponse describes a response that carries no upstream data at all -
// an RFC 9457 Problem Details document (application/problem+json).
func problemResponse(desc string) *Response {
	return &Response{
		Description: desc,
		Headers:     stdHeaders(),
		Content: map[string]MediaType{
			"application/problem+json": {Schema: &Schema{Ref: schemaProblemDetails}},
		},
	}
}

func stdHeaders() map[string]*Header {
	return map[string]*Header{
		"X-Request-ID": {
			Description: "Request identifier, echoed from the request or generated (UUIDv7).",
			Schema:      &Schema{Type: "string"},
		},
		"X-Request-Fingerprint": {
			Description: "Stable fingerprint of the request shape (method, route, header/query names).",
			Schema:      &Schema{Type: "string"},
		},
	}
}

// partialHeaders is stdHeaders plus X-Partial-Errors, which only a 206
// response carries.
func partialHeaders() map[string]*Header {
	h := stdHeaders()

	h["X-Partial-Errors"] = &Header{
		Description: "One value per failed upstream (a ClientError code, see the ClientError schema). Repeated when more than one upstream failed.",
		Schema:      &Schema{Type: "string"},
	}

	return h
}

func problemSchemas() map[string]*Schema {
	return map[string]*Schema{
		"ProblemDetails": {
			Type: "object",
			Description: "RFC 9457 Problem Details (application/problem+json). Returned only when there is no upstream " +
				"data to report: every upstream failed, or the request was rejected before reaching one.",
			Properties: map[string]*Schema{
				"type": {
					Type: "string",
					Description: "Always \"about:blank\" (RFC 9457 §4.2's own default). Deliberately never a real " +
						"URI - see `errors` for the machine-readable cause instead.",
				},
				"title": {
					Type:        "string",
					Description: "Short, human-readable summary of the highest-priority entry in `errors`.",
				},
				"status": {
					Type:        "integer",
					Description: "HTTP status code, repeated here per RFC 9457.",
				},
				"detail": {
					Type:        "string",
					Description: "Occurrence-specific explanation, when there is one.",
				},
				"errors": {
					Type: "array",
					Description: "Every distinct ClientError behind this response - always at least one. More than " +
						"one only for a multi-upstream failure where several upstreams failed differently.",
					Items: &Schema{Ref: "#/components/schemas/ClientError"},
				},
			},
		},
		"ClientError": {
			Type: "string",
			Enum: []string{
				"RATE_LIMIT_EXCEEDED",
				"PAYLOAD_TOO_LARGE",
				"UPSTREAM_BODY_TOO_LARGE",
				"UPSTREAM_UNAVAILABLE",
				"UPSTREAM_ERROR",
				"UPSTREAM_CLIENT_ERROR",
				"UPSTREAM_REDIRECT",
				"UPSTREAM_MALFORMED",
				"INTERNAL",
				"ABORTED",
				"UNAUTHORIZED",
				"VALUE_CONFLICT",
			},
		},
	}
}

func findAuthMiddleware(f aastro.FlowConfig) *aastro.MiddlewareConfig {
	for i := range f.Middlewares {
		m := &f.Middlewares[i]
		if m.Name == authMiddlewareName && m.Source == "builtin" {
			return m
		}
	}

	return nil
}

func authNote(m *aastro.MiddlewareConfig) string {
	issuer, _ := m.Config["issuer"].(string)
	audience, _ := m.Config["audience"].(string)

	switch {
	case issuer != "" && audience != "":
		return fmt.Sprintf("Requires a JWT issued by `%s` for audience `%s`.", issuer, audience)
	case issuer != "":
		return fmt.Sprintf("Requires a JWT issued by `%s`.", issuer)
	case audience != "":
		return fmt.Sprintf("Requires a JWT for audience `%s`.", audience)
	default:
		return ""
	}
}

func unauthorizedResponse() *Response {
	return &Response{
		Description: "Missing, malformed, or invalid bearer token.",
		Headers: map[string]*Header{
			"WWW-Authenticate": {
				Description: "Bearer challenge with optional error/error_description (RFC 6750).",
				Schema:      &Schema{Type: "string"},
			},
		},
		Content: map[string]MediaType{
			"application/problem+json": {Schema: &Schema{Ref: schemaProblemDetails}},
		},
	}
}

func flowExtension(f aastro.FlowConfig) *FlowExtension {
	ext := &FlowExtension{
		Streaming: f.Streaming,
		Upstreams: make([]UpstreamExtension, 0, len(f.Upstreams)),
	}

	if f.Aggregation != nil {
		agg := &AggregationExtension{
			Strategy:   f.Aggregation.Strategy,
			BestEffort: f.Aggregation.BestEffort,
		}

		if f.Aggregation.OnConflict != nil {
			agg.OnConflict = &OnConflictExtension{
				Policy:         f.Aggregation.OnConflict.Policy,
				PreferUpstream: f.Aggregation.OnConflict.Upstream,
			}
		}

		ext.Aggregation = agg
	}

	for _, m := range f.Middlewares {
		ext.Middlewares = append(ext.Middlewares, m.Name)
	}

	for _, p := range f.Plugins {
		ext.Plugins = append(ext.Plugins, p.Name)
	}

	for _, u := range f.Upstreams {
		ext.Upstreams = append(ext.Upstreams, UpstreamExtension{
			Name:           u.Name,
			Hosts:          u.Hosts,
			Path:           u.Path,
			Method:         u.Method,
			Timeout:        u.Timeout.String(),
			ForwardHeaders: u.ForwardHeaders,
			ForwardQueries: u.ForwardQueries,
			ForwardParams:  u.ForwardParams,
			TLSEnabled:     u.TLS.Enabled,
			Policy:         policyExtension(u.Policy),
			Transport:      transportExtension(u.Transport),
		})
	}

	return ext
}

func policyExtension(p aastro.PolicyConfig) *PolicyExtension {
	if reflect.DeepEqual(p, aastro.PolicyConfig{}) {
		return nil
	}

	ext := &PolicyExtension{
		HeaderBlacklist:     p.HeaderBlacklist,
		RequireBody:         p.RequireBody,
		MaxResponseBodySize: p.MaxResponseBodySize,
		FollowRedirects:     p.FollowRedirects,
		LoadBalancing:       p.LoadBalancingConfig.Mode,
	}

	if !reflect.DeepEqual(p.RetryConfig, aastro.RetryConfig{}) {
		ext.Retry = &RetryExtension{
			MaxRetries:      p.RetryConfig.MaxRetries,
			RetryOnStatuses: p.RetryConfig.RetryOnStatuses,
			BackoffDelay:    p.RetryConfig.BackoffDelay.String(),
		}
	}

	if p.CircuitBreakerConfig != (aastro.CircuitBreakerConfig{}) {
		ext.CircuitBreaker = &CircuitBreakerExtension{
			Enabled:      p.CircuitBreakerConfig.Enabled,
			MaxFailures:  p.CircuitBreakerConfig.MaxFailures,
			ResetTimeout: p.CircuitBreakerConfig.ResetTimeout.String(),
		}
	}

	return ext
}

func transportExtension(t aastro.TransportConfig) *TransportExtension {
	if t == (aastro.TransportConfig{}) || t == defaultUpstream.Transport {
		return nil
	}

	return &TransportExtension{
		MaxIdleConns:        t.MaxIdleConns,
		MaxIdleConnsPerHost: t.MaxIdleConnsPerHost,
		IdleConnTimeout:     t.IdleConnTimeout.String(),
	}
}

// propagationNote documents aggregateResponses's "default" entry, which is
// only reached for a multi-upstream flow - a single-upstream flow is
// documented by proxyResponses instead and never calls this.
func propagationNote() string {
	return "Upstream status propagated verbatim. When every failing upstream returns the same " +
		"client error status (typically 401 or 403 from a shared auth layer), that status is " +
		"forwarded instead of 502."
}

func operationID(method, path string) string {
	var b strings.Builder

	b.WriteString(strings.ToLower(method))

	for _, seg := range strings.Split(path, "/") {
		if seg == "" {
			continue
		}

		seg = strings.NewReplacer("{", "", "}", "").Replace(seg)

		b.WriteByte('_')
		b.WriteString(sanitizeID(strings.ToLower(seg)))
	}

	return b.String()
}

func sanitizeID(s string) string {
	var b strings.Builder

	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}

	return b.String()
}

func firstPathSegment(path string) string {
	for _, seg := range strings.Split(path, "/") {
		if seg != "" && !strings.HasPrefix(seg, "{") {
			return seg
		}
	}

	return ""
}

func coalesce(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}

	return ""
}
