package openapi

import (
	"fmt"
	"net/http"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/starwalkn/aastro"
)

// Options controls document generation.
type Options struct {
	// OASVersion is "3.1" (default) or "3.0".
	OASVersion string
	// Title overrides info.title; defaults to the gateway service name.
	Title string
	// APIVersion sets info.version; defaults to "0.0.0".
	APIVersion string
	// Servers become the servers[] section, in the given order.
	Servers []string
	// Extensions enables x-aastro round-trip snapshots on every operation.
	Extensions bool
	// GeneratorVersion is stamped into x-aastro.generator (e.g. aastroctl version).
	GeneratorVersion string
}

type Warning struct {
	Flow    string
	Message string
}

func (w Warning) String() string {
	return fmt.Sprintf("%s: %s", w.Flow, w.Message)
}

const (
	oasVersion31 = "3.1.0"
	oasVersion30 = "3.0.3"

	methodQuery = "QUERY"

	maxBodySizeNote = "Request bodies larger than 5 MiB are rejected with 413."

	schemaClientResponse = "#/components/schemas/ClientResponse"

	securitySchemeBearer = "bearerAuth"

	authMiddlewareName = "auth"
)

var defaultUpstream = aastro.DefaultUpstreamConfig()
var pathParamPattern = regexp.MustCompile(`\{([^}]+)\}`)

// FromConfig builds an OpenAPI document from a fully loaded gateway config.
func FromConfig(cfg aastro.Config, opts Options) (*Document, []Warning, error) {
	version, err := resolveOASVersion(opts.OASVersion)
	if err != nil {
		return nil, nil, err
	}

	doc := &Document{
		OpenAPI: version,
		Info: Info{
			Title:       coalesce(opts.Title, cfg.Gateway.Service.Name, "aastro gateway"),
			Description: "Generated by aastroctl from the aastro gateway configuration.",
			Version:     coalesce(opts.APIVersion, "0.0.0"),
		},
		Paths: make(map[string]*PathItem, len(cfg.Gateway.Routing.Flows)),
		XAastro: &RootExtension{
			Schema:    cfg.Schema,
			Generator: "aastroctl/" + coalesce(opts.GeneratorVersion, "dev"),
		},
	}

	for _, s := range opts.Servers {
		doc.Servers = append(doc.Servers, Server{URL: s})
	}

	var warnings []Warning

	rateLimited := cfg.Gateway.Routing.RateLimiter.Enabled
	tags := make(map[string]struct{})

	needEnvelope := len(cfg.Gateway.Routing.Flows) > 0

	var needAuthScheme bool

	for _, f := range cfg.Gateway.Routing.Flows {
		auth := findAuthMiddleware(f)
		if auth != nil {
			needAuthScheme = true
		}

		op := buildOperation(f, auth, rateLimited, opts.Extensions)

		if tag := firstPathSegment(f.Path); tag != "" {
			op.Tags = []string{tag}
			tags[tag] = struct{}{}
		}

		item := doc.Paths[f.Path]
		if item == nil {
			item = &PathItem{}
			doc.Paths[f.Path] = item
		}

		ws := attachOperation(item, f, op)
		warnings = append(warnings, ws...)
	}

	for t := range tags {
		doc.Tags = append(doc.Tags, Tag{Name: t})
	}
	sort.Slice(doc.Tags, func(i, j int) bool { return doc.Tags[i].Name < doc.Tags[j].Name })

	if needEnvelope || needAuthScheme {
		doc.Components = &Components{}

		if needEnvelope {
			doc.Components.Schemas = envelopeSchemas()
		}

		if needAuthScheme {
			doc.Components.SecuritySchemes = map[string]*SecurityScheme{
				securitySchemeBearer: {
					Type:         "http",
					Scheme:       "bearer",
					BearerFormat: "JWT",
					Description:  "JWT bearer token validated by the gateway auth middleware.",
				},
			}
		}
	}

	return doc, warnings, nil
}

func resolveOASVersion(v string) (string, error) {
	switch v {
	case "", "3.1":
		return oasVersion31, nil
	case "3.0":
		return oasVersion30, nil
	default:
		return "", fmt.Errorf("unsupported OpenAPI version %q (want 3.0 or 3.1)", v)
	}
}

func attachOperation(item *PathItem, f aastro.FlowConfig, op *Operation) []Warning {
	flowID := f.Method + " " + f.Path

	slot := map[string]**Operation{
		"GET":     &item.Get,
		"PUT":     &item.Put,
		"POST":    &item.Post,
		"DELETE":  &item.Delete,
		"OPTIONS": &item.Options,
		"HEAD":    &item.Head,
		"PATCH":   &item.Patch,
	}[f.Method]

	if f.Method == methodQuery {
		slot = &item.XAastroQuery

		if *slot == nil {
			*slot = op
			return []Warning{{
				Flow:    flowID,
				Message: "QUERY is not an OpenAPI 3.x method; emitted as x-aastro-query extension",
			}}
		}

		return []Warning{{Flow: flowID, Message: "duplicate method+path, operation skipped"}}
	}

	if slot == nil {
		return []Warning{{Flow: flowID, Message: fmt.Sprintf("unsupported method %q, flow skipped", f.Method)}}
	}

	if *slot != nil {
		return []Warning{{Flow: flowID, Message: "duplicate method+path, operation skipped"}}
	}

	*slot = op

	return nil
}

func buildOperation(f aastro.FlowConfig, auth *aastro.MiddlewareConfig, rateLimited, extensions bool) *Operation {
	op := &Operation{
		Summary:     summarize(f),
		OperationID: operationID(f.Method, f.Path),
		Parameters:  buildParameters(f),
	}

	notes := descriptionNotes(f)

	if auth != nil {
		op.Security = []map[string][]string{{securitySchemeBearer: {}}}

		if n := authNote(auth); n != "" {
			notes = append(notes, n)
		}
	}

	if hasRequestBody(f.Method) {
		op.RequestBody = &RequestBody{
			Description: maxBodySizeNote,
			Content: map[string]MediaType{
				"application/json": {Schema: &Schema{Type: "object"}},
			},
		}
	}

	if f.Passthrough {
		op.Responses = passthroughResponses(rateLimited)

		if auth != nil {
			op.Responses["401"] = unauthorizedResponse()
		}
		notes = append(notes,
			"Passthrough flow: the upstream response is streamed to the client unbuffered (SSE-capable); status and body are proxied as-is.")
	} else {
		op.Responses = envelopeResponses(f, rateLimited)

		if auth != nil {
			op.Responses["401"] = unauthorizedResponse()
		}
	}

	if len(notes) > 0 {
		op.Description = strings.Join(notes, "\n\n")
	}

	if extensions {
		op.XAastro = flowExtension(f)
	}

	return op
}

func summarize(f aastro.FlowConfig) string {
	if f.Passthrough {
		return fmt.Sprintf("Proxy to %s (passthrough)", upstreamNames(f.Upstreams))
	}

	if len(f.Upstreams) == 1 {
		return fmt.Sprintf("Proxy to %s", upstreamNames(f.Upstreams))
	}

	strategy := ""
	if f.Aggregation != nil {
		strategy = f.Aggregation.Strategy
	}

	return fmt.Sprintf("Aggregate %s (%s)", upstreamNames(f.Upstreams), strategy)
}

func upstreamNames(ups []aastro.UpstreamConfig) string {
	names := make([]string, 0, len(ups))
	for _, u := range ups {
		names = append(names, u.Name)
	}

	return strings.Join(names, ", ")
}

func buildParameters(f aastro.FlowConfig) []Parameter {
	var params []Parameter

	seen := make(map[string]struct{})

	for _, m := range pathParamPattern.FindAllStringSubmatch(f.Path, -1) {
		name := m[1]
		if _, ok := seen[name]; ok {
			continue
		}

		seen[name] = struct{}{}

		params = append(params, Parameter{
			Name:     name,
			In:       "path",
			Required: true,
			Schema:   &Schema{Type: "string"},
		})
	}

	for _, q := range collectForwarded(f.Upstreams, func(u aastro.UpstreamConfig) []string { return u.ForwardQueries }) {
		params = append(params, Parameter{
			Name:   q,
			In:     "query",
			Schema: &Schema{Type: "string"},
		})
	}

	for _, h := range collectForwarded(f.Upstreams, func(u aastro.UpstreamConfig) []string { return u.ForwardHeaders }) {
		switch http.CanonicalHeaderKey(h) {
		case "Accept", "Content-Type", "Authorization":
			continue
		}

		params = append(params, Parameter{
			Name:   h,
			In:     "header",
			Schema: &Schema{Type: "string"},
		})
	}

	return params
}

func collectForwarded(ups []aastro.UpstreamConfig, get func(aastro.UpstreamConfig) []string) []string {
	set := make(map[string]struct{})

	for _, u := range ups {
		for _, name := range get(u) {
			if name == "*" || strings.HasSuffix(name, "*") {
				continue
			}

			set[name] = struct{}{}
		}
	}

	out := make([]string, 0, len(set))
	for name := range set {
		out = append(out, name)
	}

	sort.Strings(out)

	return out
}

func descriptionNotes(f aastro.FlowConfig) []string {
	var notes []string

	var wildcardQueries, wildcardHeaders bool

	var headerPrefixes []string

	for _, u := range f.Upstreams {
		for _, q := range u.ForwardQueries {
			if q == "*" {
				wildcardQueries = true
			}
		}

		for _, h := range u.ForwardHeaders {
			switch {
			case h == "*":
				wildcardHeaders = true
			case strings.HasSuffix(h, "*"):
				headerPrefixes = append(headerPrefixes, h)
			}
		}
	}

	if wildcardQueries {
		notes = append(notes, "All query parameters are forwarded to at least one upstream (`forward_queries: \"*\"`).")
	}

	if wildcardHeaders {
		notes = append(notes, "All request headers are forwarded to at least one upstream (`forward_headers: \"*\"`).")
	}

	if len(headerPrefixes) > 0 {
		sort.Strings(headerPrefixes)
		notes = append(notes, fmt.Sprintf("Headers matching prefix pattern(s) %s are forwarded.", strings.Join(headerPrefixes, ", ")))
	}

	return notes
}

func hasRequestBody(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH", methodQuery:
		return true
	default:
		return false
	}
}

func envelopeResponses(f aastro.FlowConfig, rateLimited bool) map[string]*Response {
	rs := map[string]*Response{
		"200": envelopeResponse("Successful response."),
		"413": envelopeResponse("Request body exceeds the gateway limit."),
		"502": envelopeResponse("Upstream error, unavailable, or malformed response."),
		"500": envelopeResponse("Internal gateway error."),
	}

	if f.Aggregation != nil {
		if f.Aggregation.BestEffort && len(f.Upstreams) > 1 {
			rs["206"] = envelopeResponse("Partial success: some upstreams failed (best-effort aggregation). `meta.partial` is true and `errors` lists the failures.")
		}

		if f.Aggregation.Strategy == "merge" &&
			f.Aggregation.OnConflict != nil &&
			f.Aggregation.OnConflict.Policy == "error" {
			rs["409"] = envelopeResponse("Merge conflict: upstreams returned different values for the same field (`on_conflict: error`).")
		}
	}

	if rateLimited {
		rs["429"] = envelopeResponse("Rate limit exceeded.")
	}

	addPropagatedStatuses(rs, f)

	return rs
}

func passthroughResponses(rateLimited bool) map[string]*Response {
	rs := map[string]*Response{
		"200": {
			Description: "Upstream response streamed as-is. The actual status code, headers, and body are those returned by the upstream.",
			Headers:     stdHeaders(),
			Content:     map[string]MediaType{"*/*": {}},
		},
		"502": envelopeResponse("Upstream unavailable before the response started streaming."),
		"500": envelopeResponse("Internal gateway error."),
	}

	if rateLimited {
		rs["429"] = envelopeResponse("Rate limit exceeded.")
	}

	return rs
}

func envelopeResponse(desc string) *Response {
	return &Response{
		Description: desc,
		Headers:     stdHeaders(),
		Content: map[string]MediaType{
			"application/json": {Schema: &Schema{Ref: schemaClientResponse}},
		},
	}
}

func stdHeaders() map[string]*Header {
	return map[string]*Header{
		"X-Request-ID": {
			Description: "Request identifier, echoed from the request or generated (UUIDv7).",
			Schema:      &Schema{Type: "string"},
		},
		"X-Request-Fingerprint": {
			Description: "Stable fingerprint of the request shape (method, route, header/query names).",
			Schema:      &Schema{Type: "string"},
		},
	}
}

func envelopeSchemas() map[string]*Schema {
	return map[string]*Schema{
		"ClientResponse": {
			Type:        "object",
			Description: "Gateway response envelope.",
			Properties: map[string]*Schema{
				"data": {
					Type:        "object",
					Description: "Aggregated upstream payload. Shape depends on the flow's upstreams and aggregation strategy.",
				},
				"errors": {
					Type:  "array",
					Items: &Schema{Ref: "#/components/schemas/ClientError"},
				},
				"meta": {Ref: "#/components/schemas/ResponseMeta"},
			},
		},
		"ClientError": {
			Type: "string",
			Enum: []string{
				"RATE_LIMIT_EXCEEDED",
				"PAYLOAD_TOO_LARGE",
				"UPSTREAM_BODY_TOO_LARGE",
				"UPSTREAM_UNAVAILABLE",
				"UPSTREAM_ERROR",
				"UPSTREAM_CLIENT_ERROR",
				"UPSTREAM_REDIRECT",
				"UPSTREAM_MALFORMED",
				"INTERNAL",
				"ABORTED",
				"UNAUTHORIZED",
				"VALUE_CONFLICT",
			},
		},
		"ResponseMeta": {
			Type: "object",
			Properties: map[string]*Schema{
				"request_id": {Type: "string"},
				"partial": {
					Type:        "boolean",
					Description: "True when the response was assembled from a subset of upstreams (HTTP 206).",
				},
			},
		},
	}
}

func findAuthMiddleware(f aastro.FlowConfig) *aastro.MiddlewareConfig {
	for i := range f.Middlewares {
		m := &f.Middlewares[i]
		if m.Name == authMiddlewareName && m.Source == "builtin" {
			return m
		}
	}

	return nil
}

func authNote(m *aastro.MiddlewareConfig) string {
	issuer, _ := m.Config["issuer"].(string)
	audience, _ := m.Config["audience"].(string)

	switch {
	case issuer != "" && audience != "":
		return fmt.Sprintf("Requires a JWT issued by `%s` for audience `%s`.", issuer, audience)
	case issuer != "":
		return fmt.Sprintf("Requires a JWT issued by `%s`.", issuer)
	case audience != "":
		return fmt.Sprintf("Requires a JWT for audience `%s`.", audience)
	default:
		return ""
	}
}

func unauthorizedResponse() *Response {
	return &Response{
		Description: "Missing, malformed, or invalid bearer token.",
		Headers: map[string]*Header{
			"WWW-Authenticate": {
				Description: "Bearer challenge with optional error/error_description (RFC 6750).",
				Schema:      &Schema{Type: "string"},
			},
		},
		Content: map[string]MediaType{
			"application/json": {Schema: &Schema{Ref: schemaClientResponse}},
		},
	}
}

func flowExtension(f aastro.FlowConfig) *FlowExtension {
	ext := &FlowExtension{
		Passthrough: f.Passthrough,
		Upstreams:   make([]UpstreamExtension, 0, len(f.Upstreams)),
	}

	if f.Aggregation != nil {
		agg := &AggregationExtension{
			Strategy:   f.Aggregation.Strategy,
			BestEffort: f.Aggregation.BestEffort,
		}

		if f.Aggregation.OnConflict != nil {
			agg.OnConflict = &OnConflictExtension{
				Policy:         f.Aggregation.OnConflict.Policy,
				PreferUpstream: f.Aggregation.OnConflict.Upstream,
			}
		}

		ext.Aggregation = agg
	}

	for _, m := range f.Middlewares {
		ext.Middlewares = append(ext.Middlewares, m.Name)
	}

	for _, p := range f.Plugins {
		ext.Plugins = append(ext.Plugins, p.Name)
	}

	for _, u := range f.Upstreams {
		ext.Upstreams = append(ext.Upstreams, UpstreamExtension{
			Name:           u.Name,
			Hosts:          u.Hosts,
			Path:           u.Path,
			Method:         u.Method,
			Timeout:        u.Timeout.String(),
			ForwardHeaders: u.ForwardHeaders,
			ForwardQueries: u.ForwardQueries,
			ForwardParams:  u.ForwardParams,
			TLSEnabled:     u.TLS.Enabled,
			Policy:         policyExtension(u.Policy),
			Transport:      transportExtension(u.Transport),
		})
	}

	return ext
}

func policyExtension(p aastro.PolicyConfig) *PolicyExtension {
	if reflect.DeepEqual(p, aastro.PolicyConfig{}) {
		return nil
	}

	ext := &PolicyExtension{
		HeaderBlacklist:     p.HeaderBlacklist,
		AllowedStatuses:     p.AllowedStatuses,
		RequireBody:         p.RequireBody,
		MaxResponseBodySize: p.MaxResponseBodySize,
		FollowRedirects:     p.FollowRedirects,
		LoadBalancing:       p.LoadBalancingConfig.Mode,
	}

	if !reflect.DeepEqual(p.RetryConfig, aastro.RetryConfig{}) {
		ext.Retry = &RetryExtension{
			MaxRetries:      p.RetryConfig.MaxRetries,
			RetryOnStatuses: p.RetryConfig.RetryOnStatuses,
			BackoffDelay:    p.RetryConfig.BackoffDelay.String(),
		}
	}

	if p.CircuitBreakerConfig != (aastro.CircuitBreakerConfig{}) {
		ext.CircuitBreaker = &CircuitBreakerExtension{
			Enabled:      p.CircuitBreakerConfig.Enabled,
			MaxFailures:  p.CircuitBreakerConfig.MaxFailures,
			ResetTimeout: p.CircuitBreakerConfig.ResetTimeout.String(),
		}
	}

	return ext
}

func transportExtension(t aastro.TransportConfig) *TransportExtension {
	if t == (aastro.TransportConfig{}) || t == defaultUpstream.Transport {
		return nil
	}

	return &TransportExtension{
		MaxIdleConns:        t.MaxIdleConns,
		MaxIdleConnsPerHost: t.MaxIdleConnsPerHost,
		IdleConnTimeout:     t.IdleConnTimeout.String(),
	}
}

func addPropagatedStatuses(rs map[string]*Response, f aastro.FlowConfig) {
	allowed, open := allowedStatuses(f)

	if len(f.Upstreams) == 1 && !open {
		for _, status := range allowed {
			key := strconv.Itoa(status)
			if _, exists := rs[key]; exists {
				continue
			}

			rs[key] = allowedStatusResponse(status)
		}

		return
	}

	if !open {
		return
	}

	rs["default"] = &Response{
		Description: propagationNote(len(f.Upstreams)),
		Headers:     stdHeaders(),
		Content: map[string]MediaType{
			"application/json": {Schema: &Schema{Ref: schemaClientResponse}},
		},
	}
}

func allowedStatuses(f aastro.FlowConfig) (statuses []int, open bool) {
	set := make(map[int]struct{})

	for _, u := range f.Upstreams {
		if len(u.Policy.AllowedStatuses) == 0 {
			open = true
			continue
		}

		for _, s := range u.Policy.AllowedStatuses {
			set[s] = struct{}{}
		}
	}

	statuses = make([]int, 0, len(set))
	for s := range set {
		statuses = append(statuses, s)
	}

	sort.Ints(statuses)

	return statuses, open
}

func propagationNote(upstreamCount int) string {
	if upstreamCount == 1 {
		return "Upstream status propagated verbatim. A single-upstream flow acts as a proxy: " +
			"redirects and client errors (3xx, 4xx) returned by the upstream reach the client unchanged, " +
			"with the upstream body carried in `data` when it is valid JSON. " +
			"Server errors and transport failures are reported as 502 instead."
	}

	return "Upstream status propagated verbatim. When every failing upstream returns the same " +
		"client error status (typically 401 or 403 from a shared auth layer), that status is " +
		"forwarded instead of 502."
}

func allowedStatusResponse(status int) *Response {
	if status == http.StatusNoContent || status == http.StatusNotModified {
		return &Response{
			Description: "Upstream returned " + strconv.Itoa(status) + "; no response body.",
			Headers:     stdHeaders(),
		}
	}

	if status >= http.StatusOK && status < http.StatusMultipleChoices {
		return envelopeResponse("Successful response (upstream status " + strconv.Itoa(status) + ").")
	}

	return envelopeResponse("Upstream status " + strconv.Itoa(status) +
		", declared acceptable via `allowed_statuses` and propagated to the client.")
}

func operationID(method, path string) string {
	var b strings.Builder

	b.WriteString(strings.ToLower(method))

	for _, seg := range strings.Split(path, "/") {
		if seg == "" {
			continue
		}

		seg = strings.NewReplacer("{", "", "}", "").Replace(seg)

		b.WriteByte('_')
		b.WriteString(sanitizeID(strings.ToLower(seg)))
	}

	return b.String()
}

func sanitizeID(s string) string {
	var b strings.Builder

	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}

	return b.String()
}

func firstPathSegment(path string) string {
	for _, seg := range strings.Split(path, "/") {
		if seg != "" && !strings.HasPrefix(seg, "{") {
			return seg
		}
	}

	return ""
}

func coalesce(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}

	return ""
}
