package openapi

import (
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/starwalkn/aastro"
)

const (
	defaultRateLimit  = 100
	defaultRateWindow = "1s"
)

// ImportOptions controls how an OpenAPI document is converted into a gateway
// configuration.
type ImportOptions struct {
	// DefaultHost is used for scaffolded upstreams when the document carries
	// no x-aastro extensions. Falls back to servers[0], then to a placeholder.
	DefaultHost string
	// Mode selects the flow shape for scaffolded operations:
	// "proxy" (default) or "streaming". Scaffolded flows always have exactly
	// one upstream per operation, so "proxy" forwards that upstream's answer
	// as-is; it never produces an aggregating (multi-upstream) flow.
	Mode string
	// ServerPort and AdminPort seed the generated gateway skeleton.
	// Defaults: 7805 and 9090.
	ServerPort int
	AdminPort  int
}

const (
	importModeProxy     = "proxy"
	importModeStreaming = "streaming"

	defaultServerPort = 7805
	defaultAdminPort  = 9090

	placeholderHost = "https://CHANGE-ME.internal"
)

var methodSlots = []struct {
	method string
	get    func(*PathItem) *Operation
}{
	{"GET", func(i *PathItem) *Operation { return i.Get }},
	{"PUT", func(i *PathItem) *Operation { return i.Put }},
	{"POST", func(i *PathItem) *Operation { return i.Post }},
	{"DELETE", func(i *PathItem) *Operation { return i.Delete }},
	{"OPTIONS", func(i *PathItem) *Operation { return i.Options }},
	{"HEAD", func(i *PathItem) *Operation { return i.Head }},
	{"PATCH", func(i *PathItem) *Operation { return i.Patch }},
}

// ToConfig converts an OpenAPI document into a gateway configuration.
func ToConfig(doc *Document, opts ImportOptions) (aastro.Config, []Warning, error) {
	if doc == nil {
		return aastro.Config{}, nil, errors.New("nil document")
	}

	mode, err := resolveImportMode(opts.Mode)
	if err != nil {
		return aastro.Config{}, nil, err
	}

	var (
		flows        []aastro.FlowConfig
		warnings     []Warning
		rateLimited  bool
		sawExtension bool
	)

	handle := func(path, method string, op *Operation) {
		if op.XAastro != nil {
			sawExtension = true
		}

		flow, ws := convertOperation(doc, path, method, op, mode, opts)
		flows = append(flows, flow)
		warnings = append(warnings, ws...)

		if _, has429 := op.Responses["429"]; has429 {
			rateLimited = true
		}
	}

	for _, path := range sortedPaths(doc.Paths) {
		item := doc.Paths[path]
		if item == nil {
			continue
		}

		for _, slot := range methodSlots {
			if op := slot.get(item); op != nil {
				handle(path, slot.method, op)
			}
		}

		if op := item.XAastroQuery; op != nil {
			handle(path, methodQuery, op)
		}
	}

	if len(flows) == 0 {
		return aastro.Config{}, warnings, errors.New("document contains no operations")
	}

	if generatedByAastroctl(doc) && !sawExtension {
		warnings = append(warnings, Warning{
			Flow: "document",
			Message: "document was generated by aastroctl but carries no per-operation x-aastro extensions; " +
				"flows are scaffolded with defaults — re-export with --extensions for lossless import",
		})
	}

	cfg := aastro.Config{
		Schema: schemaVersion(doc),
		Gateway: aastro.GatewayConfig{
			Service: aastro.ServiceConfig{Name: serviceName(doc)},
			Server:  aastro.ServerConfig{Port: intOr(opts.ServerPort, defaultServerPort)},
			Admin:   aastro.AdminConfig{Port: intOr(opts.AdminPort, defaultAdminPort)},
			Routing: aastro.RoutingConfig{Flows: flows},
		},
	}

	if rateLimited {
		cfg.Gateway.Routing.RateLimiter = aastro.RateLimiterConfig{
			Enabled: true,
			Config:  map[string]interface{}{"limit": defaultRateLimit, "window": defaultRateWindow},
		}

		warnings = append(warnings, Warning{
			Flow:    "gateway",
			Message: "429 responses found in the document; rate limiter enabled with default settings (limit=100, window=1s) — tune before deploying",
		})
	}

	return cfg, warnings, nil
}

func resolveImportMode(mode string) (string, error) {
	switch mode {
	case "", importModeProxy:
		return importModeProxy, nil
	case importModeStreaming:
		return importModeStreaming, nil
	default:
		return "", fmt.Errorf("unsupported import mode %q (want proxy or streaming)", mode)
	}
}

func convertOperation(doc *Document, path, method string, op *Operation, mode string, opts ImportOptions) (aastro.FlowConfig, []Warning) {
	if op.XAastro != nil {
		return reconstructFlow(path, method, op)
	}

	return scaffoldFlow(doc, path, method, op, mode, opts)
}

func reconstructFlow(path, method string, op *Operation) (aastro.FlowConfig, []Warning) {
	ext := op.XAastro
	flowID := method + " " + path

	var warnings []Warning

	flow := aastro.FlowConfig{
		Path:      path,
		Method:    method,
		Streaming: ext.Streaming,
	}

	if ext.Aggregation != nil {
		flow.Aggregation = reconstructAggregation(ext.Aggregation)
	}

	for _, u := range ext.Upstreams {
		up := aastro.UpstreamConfig{
			Name:           u.Name,
			Hosts:          aastro.AddrList(u.Hosts),
			Path:           u.Path,
			Method:         u.Method,
			ForwardHeaders: u.ForwardHeaders,
			ForwardQueries: u.ForwardQueries,
			ForwardParams:  u.ForwardParams,
		}

		if len(up.Hosts) == 0 {
			up.Hosts = aastro.AddrList{placeholderHost}
			warnings = append(warnings, Warning{
				Flow:    flowID,
				Message: fmt.Sprintf("upstream %q has no hosts in x-aastro; placeholder inserted", u.Name),
			})
		}

		if u.Timeout != "" {
			d, err := time.ParseDuration(u.Timeout)
			if err != nil {
				warnings = append(warnings, Warning{
					Flow:    flowID,
					Message: fmt.Sprintf("upstream %q has unparsable timeout %q; gateway default will apply", u.Name, u.Timeout),
				})
			} else {
				up.Timeout = d
			}
		}

		if u.Policy != nil {
			up.Policy = reconstructPolicy(u.Policy, flowID, u.Name, &warnings)
		}

		if u.Transport != nil {
			up.Transport = aastro.TransportConfig{
				MaxIdleConns:        u.Transport.MaxIdleConns,
				MaxIdleConnsPerHost: u.Transport.MaxIdleConnsPerHost,
				IdleConnTimeout:     parseDurationOr(u.Transport.IdleConnTimeout, 0, flowID, u.Name, "transport idle_conn_timeout", &warnings),
			}
		} else {
			up.Transport = defaultUpstream.Transport
		}

		if u.TLSEnabled {
			up.TLS = aastro.TLSConfig{Enabled: true}

			warnings = append(warnings, Warning{
				Flow: flowID,
				Message: fmt.Sprintf(
					"upstream %q TLS restored with system roots; certificate/CA paths are not stored in specs — re-add them if the upstream uses mTLS or a private CA",
					u.Name,
				),
			})
		}

		flow.Upstreams = append(flow.Upstreams, up)
	}

	if len(ext.Plugins) > 0 {
		warnings = append(warnings, Warning{
			Flow: flowID,
			Message: fmt.Sprintf(
				"flow used plugin(s) %s; plugin configurations are not stored in specs — re-add them manually",
				strings.Join(ext.Plugins, ", "),
			),
		})
	}

	if len(ext.Middlewares) > 0 {
		warnings = append(warnings, Warning{
			Flow: flowID,
			Message: fmt.Sprintf(
				"flow used middleware(s) %s; middleware configurations are not stored in specs — re-add them manually",
				strings.Join(ext.Middlewares, ", "),
			),
		})
	}

	return flow, warnings
}

func reconstructAggregation(ext *AggregationExtension) *aastro.AggregationConfig {
	agg := &aastro.AggregationConfig{
		Strategy:   ext.Strategy,
		BestEffort: ext.BestEffort,
	}

	if ext.OnConflict != nil {
		agg.OnConflict = &aastro.OnConflictConfig{
			Policy:   ext.OnConflict.Policy,
			Upstream: ext.OnConflict.PreferUpstream,
		}
	}

	return agg
}

func reconstructPolicy(p *PolicyExtension, flowID, upstream string, warnings *[]Warning) aastro.PolicyConfig {
	policy := aastro.PolicyConfig{
		HeaderBlacklist:     p.HeaderBlacklist,
		RequireBody:         p.RequireBody,
		MaxResponseBodySize: p.MaxResponseBodySize,
		FollowRedirects:     p.FollowRedirects,
		LoadBalancingConfig: aastro.LoadBalancingConfig{Mode: p.LoadBalancing},
	}

	if p.Retry != nil {
		policy.RetryConfig = aastro.RetryConfig{
			MaxRetries:      p.Retry.MaxRetries,
			RetryOnStatuses: p.Retry.RetryOnStatuses,
			BackoffDelay:    parseDurationOr(p.Retry.BackoffDelay, 0, flowID, upstream, "retry backoff_delay", warnings),
		}
	}

	if p.CircuitBreaker != nil {
		policy.CircuitBreakerConfig = aastro.CircuitBreakerConfig{
			Enabled:      p.CircuitBreaker.Enabled,
			MaxFailures:  p.CircuitBreaker.MaxFailures,
			ResetTimeout: parseDurationOr(p.CircuitBreaker.ResetTimeout, 0, flowID, upstream, "circuit_breaker reset_timeout", warnings),
		}
	}

	return policy
}

func parseDurationOr(raw string, fallback time.Duration, flowID, upstream, field string, warnings *[]Warning) time.Duration {
	if raw == "" {
		return fallback
	}

	d, err := time.ParseDuration(raw)
	if err != nil {
		*warnings = append(*warnings, Warning{
			Flow:    flowID,
			Message: fmt.Sprintf("upstream %q has unparsable %s %q; zero value used", upstream, field, raw),
		})

		return fallback
	}

	return d
}

func scaffoldFlow(doc *Document, path, method string, op *Operation, mode string, opts ImportOptions) (aastro.FlowConfig, []Warning) {
	flowID := method + " " + path

	var warnings []Warning

	host, hostWarning := resolveScaffoldHost(doc, opts)
	if hostWarning != "" {
		warnings = append(warnings, Warning{Flow: flowID, Message: hostWarning})
	}

	upstream := aastro.UpstreamConfig{
		Name:  upstreamNameFor(op, method, path),
		Hosts: aastro.AddrList{host},
		Path:  path,
	}

	for _, p := range op.Parameters {
		switch p.In {
		case "query":
			upstream.ForwardQueries = append(upstream.ForwardQueries, p.Name)
		case "header":
			upstream.ForwardHeaders = append(upstream.ForwardHeaders, p.Name)
		}
	}

	flow := aastro.FlowConfig{
		Path:      path,
		Method:    method,
		Upstreams: []aastro.UpstreamConfig{upstream},
	}

	streaming := isStreamingOperation(op)

	if mode == importModeStreaming || streaming {
		flow.Streaming = true

		if streaming && mode != importModeStreaming {
			warnings = append(warnings, Warning{
				Flow:    flowID,
				Message: "streamed */* response detected; scaffolded as a streaming flow",
			})
		}
	}
	// else: proxy mode. Scaffolded flows always have exactly one upstream,
	// so no Aggregation is set — it would never be read (see Router.dispatch).

	if len(op.Security) > 0 {
		warnings = append(warnings, Warning{
			Flow:    flowID,
			Message: "operation declares a security requirement; configure the auth middleware (and forward the Authorization header if the upstream needs it)",
		})
	}

	return flow, warnings
}

func isStreamingOperation(op *Operation) bool {
	resp, ok := op.Responses["200"]
	if !ok || resp == nil {
		return false
	}

	_, streaming := resp.Content["*/*"]

	return streaming
}

func generatedByAastroctl(doc *Document) bool {
	return doc.XAastro != nil && strings.HasPrefix(doc.XAastro.Generator, "aastroctl/")
}

func resolveScaffoldHost(doc *Document, opts ImportOptions) (host, warning string) {
	if opts.DefaultHost != "" {
		return opts.DefaultHost, ""
	}

	if len(doc.Servers) > 0 && doc.Servers[0].URL != "" {
		return doc.Servers[0].URL, ""
	}

	return placeholderHost, "no --default-host and no servers[] in the document; placeholder host inserted"
}

func upstreamNameFor(op *Operation, method, path string) string {
	if op.OperationID != "" {
		return sanitizeID(strings.ToLower(op.OperationID))
	}

	return operationID(method, path)
}

func sortedPaths(paths map[string]*PathItem) []string {
	out := make([]string, 0, len(paths))
	for p := range paths {
		out = append(out, p)
	}

	sort.Strings(out)

	return out
}

func schemaVersion(doc *Document) string {
	if doc.XAastro != nil && doc.XAastro.Schema != "" {
		return doc.XAastro.Schema
	}

	return "v1"
}

func serviceName(doc *Document) string {
	if doc.Info.Title != "" {
		return doc.Info.Title
	}

	return "aastro"
}

func intOr(v, fallback int) int {
	if v > 0 {
		return v
	}

	return fallback
}
